# Generated by Django 5.2 on 2025-04-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('phonenumber', models.CharField(max_length=122)),
                ('desc', models.TextField()),
            ],
        ),
    ]
